"""empty message

Revision ID: c09e1264ad5f
Revises: 
Create Date: 2020-05-28 08:36:34.221230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c09e1264ad5f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklist_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blacklist_tokens")),
        sa.UniqueConstraint("token", name=op.f("uq_blacklist_tokens_token")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=40), nullable=False),
        sa.Column("password", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("surname", sa.String(length=100), nullable=False),
        sa.Column("registration_date", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("blacklist_tokens")
    # ### end Alembic commands ###
